name: TerraZero_Dev Terraform Plan

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/TerraZero_Dev/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git to use the GITHUB_TOKEN
        run: |
          git config --global url."https://oauth2:${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
  
      - name: Configure AWS credentials using OIDC
        id: configure-aws-creds
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_MANAGEMENT_ACCOUNT_ID }}:role/intraverse-ops-github-actions
          aws-region: us-east-1
  
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.4.6

      - name: Terraform Init
        run: terraform init
        working-directory: terraform/TerraZero_Dev
    
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform/TerraZero_Dev

