name: TerraZero_Prod DCV Server AMI
description: Builds the DCV Server AMI for the TerraZero Prod environment

on:
  workflow_dispatch:
    inputs:
      dcv_version:
        description: 'DCV Version'
        required: true
        default: '1.3.11'
      game_version:
        description: 'Intraverse Unity Client Version'
        required: true
        default: '1.3.6'

env:
  AWS_REGION: us-east-1
  AWS_MANAGEMENT_ACCOUNT_ID: 123456789012

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git to use the GITHUB_TOKEN
        run: |
          git config --global url."https://oauth2:${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
  
      - name: Configure AWS credentials using OIDC
        id: configure-aws-creds
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_MANAGEMENT_ACCOUNT_ID }}:role/intraverse-ops-github-actions
          aws-region: us-east-1
  
      - name: Setup Packer
        uses: hashicorp/setup-packer@v1
        with:
          packer-version: 1.11.2

      - name: Build DCV Server AMI
        run: packer build -var 'game_version=${{ inputs.game_version }}' -var 'dcv_version=${{ inputs.dcv_version }}' packer/dcv-server-host/dcv-server-ami.pkr.hcl
    

